# scoring.toml
# Step 4: similarity + low-logP continuous scoring

run_type        = "scoring"
json_out_config = "step4_scoring_config.json"

[parameters]
smiles_file     = "step3_samples.csv"  # from Step 3
output_file     = "step4_scored.csv"   # now honored by REINVENT4

[scoring]
type     = "arithmetic_mean"           # simple average of both endpoints
parallel = false

# — Component 1: Tanimoto similarity to diphenhydramine —
[[scoring.component]]
[scoring.component.TanimotoDistance]
  [[scoring.component.TanimotoDistance.endpoint]]
  name              = "Similarity to diphenhydramine"
  weight            = 1
  params.smiles     = ["CN(C)CCOC(c1ccccc1)c2ccccc2"]
  params.radius     = 3
  params.use_counts = true
  params.use_features = false

# — Component 2: continuous low-logP preference —
[[scoring.component]]
[scoring.component.SlogP]
  [[scoring.component.SlogP.endpoint]]
  name           = "low logP preference"
  weight         = 1
  # reverse_sigmoid will map:
  #   raw logP ≤ –5.0 → score ≈ 1.0
  #   raw logP ≥  3.0 → score ≈ 0.0
  #   in between → smooth sigmoid drop-off controlled by k
  transform.type = "reverse_sigmoid"
  transform.low  = -5.0
  transform.high =  3.0
  transform.k    =  5.0

